import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Wrapper from "./wrapper";
import Navbar from "@/components/dev component/Navbar";
import Footer from "@/components/dev component/Footer";

const inter = Inter({subsets: ["latin"], variable: "--font-inter"});

export const metadata: Metadata = {
  title: "Anglara Task App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Wrapper>
        <body
          suppressHydrationWarning={true}
          className={`${inter.variable}  antialiased`}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </Wrapper>
    </html>
  );
}
